### ISSUE TITLE
Split cleaner for mainnet and testnet

### ISSUE THREAD

**Issue by zgrguric** [Xahau/Validation-Ledger-Tx-Store-to-xPOP#6]
Split cleaner or configuration so different configurations can be added for cleanup of testnet and mainnet data.

**Comment by WietseWind** [comment]
For custom cleaning, you can use the provided script, possibly disable the default cleaning in the docker-compose file;

https://github.com/Xahau/Validation-Ledger-Tx-Store-to-xPOP/blob/main/scripts/cleanup.sh#L13

^^ instead of cleaning the entire store there, you could clean one level deeper (e.g. `store/1` for testnet, `store/0` for mainnet) and then clean with depth 2 instead of 3 :)
